### PR TITLE
adding git committer info to dockerfile to fix failing ci

### PR DESCRIPTION
**Pull request by tinakurian**
Fixing CI by adding git committer information.

### CODE REVIEW

**Review by sbose78 — CHANGES_REQUESTED** [review]
Please do the same in Dockerfile.tools in openshift-ci/

**Comment by tinakurian** [comment]
> Please do the same in Dockerfile.tools in openshift-ci/

done here: 8722dcee76da0a11bcbc25ca6d23a91ee4671ef8

**Review by corinnekrych — APPROVED** [review]

**Review by sbose78 — APPROVED** [review]
Taking in this change, because we need this anyway.

**Comment by sbose78** [comment]
need this to test https://github.com/openshift/release/pull/3521

**Pull request merged**
