### PR TITLE
ODC-405 Add GitSource API

### PR DESCRIPTION
**Pull request by alexeykazakov**
Moving GitSource API to devconsole-api repo.

Some files (`deploy/*`, `cmd/*`) are not used but required by operator-sdk.

### CODE REVIEW

**Comment by sbose78** [comment]
This should have only the canonical definitions for the GitSource API - along the lines of 
- openshift API https://github.com/openshift/api . 
- The component API ( a different one, not ours ) https://github.com/snowdrop/component-api
- The CRI API https://github.com/kubernetes/cri-api

We should get rid of cmd/* , main.go , deploy/* . Typically, the APIs shouldn't have dependencies on operator-sdk. The initial generation of the controller could be in the devconsole-operator, and then we should move out the `pkg/apis` to this repository.

**Comment by alexeykazakov** [comment]
> Typically, the APIs shouldn't have dependencies on operator-sdk.

This API is API used by operator. So, I don't think it's so critical not to have dependencies on operator-sdk.
It actually would be convenient to have some tooling available to generate new API in the repo. IMO we should discuss it with the operator guys. Maybe some optional parameters would relax some validation rules and allow operator-sdk generate APIs without requesting cmd and deploy.
But for now I'm OK to drop operator-sdk support in this repo.

**Comment by alexeykazakov** [comment]
I've removed dependency on operator-sdk. Still not sure if I should have though :)

**Comment by sbose78** [comment]
Thank you! :) 

> This API is API used by operator.

Right, today it is. However, it might not necessarily be that way always - as in, there could be other Golang packages which might import and use our "API" library :) The same way `openshift/api` is maintained and consumed by non first class citizens of openshift.

Yes, it is important to provide an easy way to add an API. We should add a readme later on:
1. generate using operator-sdk.
2. copy over to this repo maybe , or directly generate it here and commit only specific files?

**Review by sbose78 — APPROVED** [review]

**Comment by alexeykazakov** [comment]
> it might not necessarily be that way always - as in, there could be other Golang packages which might import and use our "API" library 

Well, the operator-sdk was only a build/code-generation level. You don't need operator-sdk to consume/use the API.
But anyway, I'm fine with not relaying on operator-sdk in the API repo for now at all.

> Yes, it is important to provide an easy way to add an API. We should add a readme later on

There is already (in this PR) something in the readme:
- Use operator-sdk to generate the code in devconsole-operator repo
- Move the generated code to devconsole-api

We can improve it later.

Thanks for the review!

**Pull request merged**
